name: PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  pr:
    runs-on: windows-latest
    permissions:
      packages: read
      contents: read
    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: .NET installieren
        uses: actions/setup-dotnet@v4

      - name: GitHub Package Manager registrieren
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/co-IT/index.json"

      - name: Install Tools
        run: dotnet tool restore

      - name: Install Dependencies
        run: dotnet restore

      - name: Lint
        run: dotnet csharpier check .

      - name: Anwendung bauen
        run: dotnet publish -c Release -r win-x64 ${{ github.workspace }}\coIT.Toolkit.Lexoffice.GdiExport.csproj --property:PublishProfile="FolderProfile"

      - name: Installer bauen
        uses: caphyon/advinst-github-action@v2.0
        with:
          advinst-version: '21.9'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\coIT.Toolkit.Lexoffice.GdiExport.Installer.aip
          aip-build-name: DefaultBuild
          aip-package-name: coIT.Toolkit.Lexoffice.GdiExport.Installer-0.0.0.msi
          aip-output-dir: ${{ github.workspace }}\setup
          aip-commands: |
            SetVersion 0.0.0

      - name: Update json erstellen
        env:
          VERSION: 0.0.0
        run: |
          # JSON String erstellen
          $jsonString = '{"RegistryKey":"HKUD\\Software\\\\co-IT.eu GmbH\\Lexoffice Gdi Export\\Version", "Version":"' + $env:VERSION + '"}'

          # Datei erstellen
          $jsonString | Set-Content -Path advinst_update.json

          # Dbug Ausgabe
          Write-Output (Resolve-Path advinst_update.json)
          Get-Content advinst_update.json
